In [1]:
from aistudio.estimator3 import Estimator

In [2]:
import torch
import torchvision
import torchvision.transforms as transforms

In [11]:
transform = transforms.Compose(
    [transforms.ToTensor(),
     transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])

trainset = torchvision.datasets.CIFAR10(root='./data', train=True,
                                        download=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=4,
                                          shuffle=False, num_workers=2)

testset = torchvision.datasets.CIFAR10(root='./data', train=False,
                                       download=True, transform=transform)
testloader = torch.utils.data.DataLoader(testset, batch_size=4,
                                         shuffle=False, num_workers=2)

classes = ('plane', 'car', 'bird', 'cat',
           'deer', 'dog', 'frog', 'horse', 'ship', 'truck')

Files already downloaded and verified
Files already downloaded and verified


In [ ]:
input_data_torch = trainset.data
input_data_torch = torch.div(input_data_torch,255.)
input_data_torch = torch.add(input_data_torch,-0.1307)
input_data_torch = torch.div(input_data_torch,0.3081)
input_data_torch = input_data_torch.unsqueeze(1)
input_labels_torch = train_dataset.targets
# Convert Tensor to Numpy
input_data = input_data_torch.numpy()
input_labels = input_labels_torch.numpy()

In [24]:
for data, label in trainloader:
    print(data.shape)
    print(label.shape)
    print(data[0].shape)
    print(data[0])
    break

torch.Size([4, 3, 32, 32])
torch.Size([4])
torch.Size([3, 32, 32])
tensor([[[-0.5373, -0.6627, -0.6078,  ...,  0.2392,  0.1922,  0.1608],
         [-0.8745, -1.0000, -0.8588,  ..., -0.0353, -0.0667, -0.0431],
         [-0.8039, -0.8745, -0.6157,  ..., -0.0745, -0.0588, -0.1451],
         ...,
         [ 0.6314,  0.5765,  0.5529,  ...,  0.2549, -0.5608, -0.5843],
         [ 0.4118,  0.3569,  0.4588,  ...,  0.4431, -0.2392, -0.3490],
         [ 0.3882,  0.3176,  0.4039,  ...,  0.6941,  0.1843, -0.0353]],

        [[-0.5137, -0.6392, -0.6235,  ...,  0.0353, -0.0196, -0.0275],
         [-0.8431, -1.0000, -0.9373,  ..., -0.3098, -0.3490, -0.3176],
         [-0.8118, -0.9451, -0.7882,  ..., -0.3412, -0.3412, -0.4275],
         ...,
         [ 0.3333,  0.2000,  0.2627,  ...,  0.0431, -0.7569, -0.7333],
         [ 0.0902, -0.0353,  0.1294,  ...,  0.1608, -0.5137, -0.5843],
         [ 0.1294,  0.0118,  0.1137,  ...,  0.4431, -0.0745, -0.2784]],

        [[-0.5059, -0.6471, -0.6627,  ..., -0.152

In [13]:
input_data_torch = trainset.data

In [14]:
print(input_data_torch.shape)

(50000, 32, 32, 3)


In [51]:
aaa=input_data_torch[0]/255.
aaa = aaa - 0.5
aaa = aaa / 0.5
print(aaa.shape)
print(aaa)
bbb = np.swapaxes(aaa,0,2)
bbb = np.swapaxes(bbb,1,2)
ccc = aaa.transpose(2,0,1)
print(bbb.shape)
print(bbb)
print(ccc.shape)
print(ccc)

(32, 32, 3)
[[[-0.5372549  -0.51372549 -0.50588235]
  [-0.6627451  -0.63921569 -0.64705882]
  [-0.60784314 -0.62352941 -0.6627451 ]
  ...
  [ 0.23921569  0.03529412 -0.15294118]
  [ 0.19215686 -0.01960784 -0.2       ]
  [ 0.16078431 -0.02745098 -0.19215686]]

 [[-0.8745098  -0.84313725 -0.84313725]
  [-1.         -1.         -1.        ]
  [-0.85882353 -0.9372549  -1.        ]
  ...
  [-0.03529412 -0.30980392 -0.56862745]
  [-0.06666667 -0.34901961 -0.60784314]
  [-0.04313725 -0.31764706 -0.55294118]]

 [[-0.80392157 -0.81176471 -0.83529412]
  [-0.8745098  -0.94509804 -1.        ]
  [-0.61568627 -0.78823529 -0.9372549 ]
  ...
  [-0.0745098  -0.34117647 -0.60784314]
  [-0.05882353 -0.34117647 -0.60784314]
  [-0.14509804 -0.42745098 -0.67058824]]

 ...

 [[ 0.63137255  0.33333333 -0.24705882]
  [ 0.57647059  0.2        -0.73333333]
  [ 0.55294118  0.2627451  -0.79607843]
  ...
  [ 0.25490196  0.04313725 -0.45098039]
  [-0.56078431 -0.75686275 -0.94509804]
  [-0.58431373 -0.73333333 -0.84

In [25]:
from PIL import Image

In [31]:
img_path = "/home/sky/dev/aistudio/data/MNIST-dataset/MNIST/training/0/1.png"
im = Image.open(img_path)

In [35]:
import numpy
I = numpy.asarray(Image.open(img_path))
im2 = Image.fromarray(numpy.uint8(I))
print(I.shape)
print(I)

(28, 28)
[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0  51 159 253
  159  50   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0  48 238 252 252
  252 237   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0  54 227 253 252 239
  233 252  57   6   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0  10  60 224 252 253 252 202
   84 252 253 122   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0 163 252 2

In [33]:
im2

In [55]:
img_path = "/home/sky/dev/aistudio/data/image-dataset/image-datasets/cifar-10/images/0/29.png"
im = Image.open(img_path)

import numpy
I = numpy.asarray(Image.open(img_path))
im2 = Image.fromarray(numpy.uint8(I))
print(I.shape)
print(I)

(32, 32, 3)
[[[202 204 199]
  [202 204 199]
  [204 206 201]
  ...
  [207 208 200]
  [205 206 199]
  [203 204 198]]

 [[206 208 203]
  [206 208 203]
  [207 209 204]
  ...
  [210 211 205]
  [208 209 203]
  [206 207 201]]

 [[210 212 207]
  [211 213 208]
  [212 214 210]
  ...
  [214 214 210]
  [212 213 208]
  [210 211 206]]

 ...

 [[218 217 222]
  [210 209 214]
  [194 194 198]
  ...
  [243 242 247]
  [244 242 247]
  [243 243 247]]

 [[219 218 223]
  [217 216 221]
  [216 216 220]
  ...
  [241 240 245]
  [241 240 245]
  [241 240 245]]

 [[217 216 221]
  [216 215 220]
  [217 216 221]
  ...
  [239 238 243]
  [239 238 243]
  [240 238 243]]]


In [37]:
import numpy as np

x = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
print(x.shape)
print(x)

(2, 2, 2)
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [39]:
bbb= np.array([[1,1],[2,2]])
ccc = np.array([1])

In [40]:
print(bbb.shape)
print(ccc.shape)

(2, 2)
(1,)


In [43]:
ddd = np.array([[[1,1],[2,2]],[[3,3],[4,4]]])

In [44]:
print(ddd.shape)

(2, 2, 2)


In [45]:
dddd = np.swapaxes(ddd,0,1)

In [46]:
print(dddd.shape)

(2, 2, 2)


In [47]:
dddd

array([[[1, 1],
        [3, 3]],

       [[2, 2],
        [4, 4]]])